added provisioning dir
allegro-actions/artifactory-publish pull request #15
Opened 2021-08-18 13:31 UTC by ar4s

2021-08-18 15:44 UTC, bgalek requested changes
please remove /dist/folder from PR :)

2021-08-19 12:15 UTC, ar4s commented
> @ar4s imo this will create double timestamp (it's artifactory feature)
I tested that and looks fine :) I was strongly inspired by what is in the tycho.

2021-08-19 17:11 UTC, bgalek commented
@ar4s ok, LGTM then! if you tested that version, I'll can release new version ;)

2021-08-19 22:33 UTC, bgalek commented on utils/provisioning.js
> +      fs.mkdirSync(provisioningDir);
this is a problem for multimodule applications ;(
https://github.com/allegro-internal/opbox-core/tree/master/core/provisioning

2021-08-20 10:02 UTC, merged